# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'patchwork.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from array import array
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.Qt import Qt
import numpy as np

WHITE = (255,255,255)
BLACK = (0,0,0)

class Ui_MainWindow(object):

        def setupUi(self, MainWindow):
                MainWindow.setObjectName("Patchwork")
                MainWindow.resize(1290, 750)
                self.centralwidget = QtWidgets.QWidget(MainWindow)
                self.centralwidget.setObjectName("centralwidget")
                self.MainWindow_2 = QtWidgets.QTabWidget(self.centralwidget)
                # set tab window size
                self.MainWindow_2.setGeometry(QtCore.QRect(330, 10, 920, 700))
                self.MainWindow_2.setTabsClosable(False)
                self.MainWindow_2.setObjectName("MainWindow_2")
                self.p1 = QtWidgets.QWidget()
                self.p1.setObjectName("p1")
                self.p1quilt = QtWidgets.QTableWidget(self.p1)
                # set table size
                self.p1quilt.setGeometry(QtCore.QRect(10, 30, 596, 596))
                self.p1quilt.setMaximumSize(QtCore.QSize(16777215, 16777215))
                self.p1quilt.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
                self.p1quilt.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)

                # Initialize the p1 quilt!
                self.p1quilt.setObjectName("p1quilt")
                self.p1quilt.setColumnCount(9)
                self.p1quilt.setRowCount(9)
                for i in range(9):
                        item = QtWidgets.QTableWidgetItem()
                        # item.setFlags(QtCore.Qt.ItemIsEnabled)
                        self.p1quilt.setVerticalHeaderItem(i, item)
                for i in range(9):
                        item = QtWidgets.QTableWidgetItem()
                        # item.setFlags(QtCore.Qt.ItemIsEnabled)
                        self.p1quilt.setHorizontalHeaderItem(i, item)
                for i in range(9):
                        for j in range(9):
                                item = QtWidgets.QTableWidgetItem()
                                brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
                                brush.setStyle(QtCore.Qt.SolidPattern)
                                item.setBackground(brush)
                                self.p1quilt.setItem(i, j, item)
                self.p1quilt.horizontalHeader().setVisible(False)
                self.p1quilt.horizontalHeader().setDefaultSectionSize(66)
                self.p1quilt.horizontalHeader().setMinimumSectionSize(32)
                self.p1quilt.verticalHeader().setVisible(False)
                self.p1quilt.verticalHeader().setDefaultSectionSize(66)
                self.p1quilt.verticalHeader().setMinimumSectionSize(32)

                # initialize the p2 quilt!
                self.p2 = QtWidgets.QWidget()
                self.p2.setObjectName("p2")
                self.p2quilt = QtWidgets.QTableWidget(self.p2)
                self.p2quilt.setGeometry(QtCore.QRect(10, 30, 596, 596))
                self.p2quilt.setMaximumSize(QtCore.QSize(16777215, 16777215))
                self.p2quilt.setLineWidth(1)
                self.p2quilt.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
                self.p2quilt.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
                self.p2quilt.setObjectName("p2quilt")
                self.p2quilt.setColumnCount(9)
                self.p2quilt.setRowCount(9)
                for i in range(9):
                        item = QtWidgets.QTableWidgetItem()
                        self.p2quilt.setVerticalHeaderItem(i, item)
                for i in range(9):
                        item = QtWidgets.QTableWidgetItem()
                        self.p2quilt.setHorizontalHeaderItem(i, item)
                
                for i in range(9):
                        for j in range(9):
                                item = QtWidgets.QTableWidgetItem()
                                brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
                                brush.setStyle(QtCore.Qt.SolidPattern)
                                item.setBackground(brush)
                                self.p2quilt.setItem(i, j, item)
                self.p2quilt.horizontalHeader().setVisible(False)
                self.p2quilt.horizontalHeader().setDefaultSectionSize(66)
                self.p2quilt.horizontalHeader().setMinimumSectionSize(32)
                self.p2quilt.verticalHeader().setVisible(False)
                self.p2quilt.verticalHeader().setDefaultSectionSize(66)
                self.p2quilt.verticalHeader().setMinimumSectionSize(32)

                self.turn_marker_p1 = QtWidgets.QLabel(self.p1)
                self.turn_marker_p1.setGeometry(QtCore.QRect(10, 10, 181, 21))
                self.turn_marker_p1.setObjectName("turn_marker_p1")
                self.turn_marker_p2 = QtWidgets.QLabel(self.p2)
                self.turn_marker_p2.setGeometry(QtCore.QRect(10, 10, 181, 21))
                self.turn_marker_p2.setObjectName("turn_marker_p2")
                self.turn_marker_board = QtWidgets.QLabel(self.p1)
                self.turn_marker_board.setGeometry(QtCore.QRect(10, 10, 181, 21))
                self.turn_marker_board.setObjectName("turn_marker_board")
                self.ErrorMessage_p1 = QtWidgets.QLabel(self.p1)
                self.ErrorMessage_p1.setGeometry(QtCore.QRect(450, 10, 200, 20))
                font = QtGui.QFont()
                font.setBold(True)
                font.setWeight(75)
                self.ErrorMessage_p1.setFont(font)
                self.ErrorMessage_p1.setObjectName("ErrorMessage_p1")
                self.MoveAheadButton_p1 = QtWidgets.QPushButton(self.p1)
                self.MoveAheadButton_p1.setGeometry(QtCore.QRect(636, 30, 250, 80))
                self.MoveAheadButton_p1.setObjectName("MoveAheadButton_p1")
                self.PlacePieceButton_p1 = QtWidgets.QPushButton(self.p1)
                self.PlacePieceButton_p1.setGeometry(QtCore.QRect(636, 130, 250, 80))
                self.PlacePieceButton_p1.setObjectName("PlacePieceButton_p1")
                self.DownloadInstructionsButton_p1 = QtWidgets.QPushButton(self.p1)
                self.DownloadInstructionsButton_p1.setGeometry(QtCore.QRect(636, 230, 250, 80))
                self.DownloadInstructionsButton_p1.setObjectName("DownloadInstructionsButton_p1")
                self.inventory_p1 = QtWidgets.QLabel(self.p1)
                self.inventory_p1.setGeometry(QtCore.QRect(636, 500, 200, 150))
                font = QtGui.QFont()
                font.setFamily("Sylfaen")
                font.setPointSize(12)
                self.inventory_p1.setFont(font)
                self.inventory_p1.setObjectName("inventory_p1")
                self.instructions_text_p1 = QtWidgets.QLabel(self.p1)
                self.instructions_text_p1.setGeometry(QtCore.QRect(10, 640, 431, 20))
                font = QtGui.QFont()
                font.setPointSize(6)
                self.instructions_text_p1.setFont(font)
                self.instructions_text_p1.setObjectName("instructions_text_p1")
                self.MainWindow_2.addTab(self.p1, "")
                self.ErrorMessage_p2 = QtWidgets.QLabel(self.p2)
                self.ErrorMessage_p2.setGeometry(QtCore.QRect(450, 10, 200, 20))
                font = QtGui.QFont()
                font.setBold(True)
                font.setWeight(75)
                self.ErrorMessage_p2.setFont(font)
                self.ErrorMessage_p2.setObjectName("ErrorMessage_p2")
                self.PlacePieceButton_p2 = QtWidgets.QPushButton(self.p2)
                self.PlacePieceButton_p2.setGeometry(QtCore.QRect(636, 130, 250, 80))
                self.PlacePieceButton_p2.setObjectName("PlacePieceButton_p2")
                self.DownloadInstructionsButton_p2 = QtWidgets.QPushButton(self.p2)
                self.DownloadInstructionsButton_p2.setGeometry(QtCore.QRect(636, 230, 250, 80))
                self.DownloadInstructionsButton_p2.setObjectName("DownloadInstructionsButton_p2")
                self.inventory_p2 = QtWidgets.QLabel(self.p2)
                self.inventory_p2.setGeometry(QtCore.QRect(636, 500, 200, 150))
                font = QtGui.QFont()
                font.setFamily("Sylfaen")
                font.setPointSize(12)
                self.inventory_p2.setFont(font)
                self.inventory_p2.setObjectName("inventory_p2")
                self.MoveAheadButton_p2 = QtWidgets.QPushButton(self.p2)
                self.MoveAheadButton_p2.setGeometry(QtCore.QRect(636, 30, 250, 80))
                self.MoveAheadButton_p2.setObjectName("MoveAheadButton_p2")
                self.instructions_text_p2 = QtWidgets.QLabel(self.p2)
                self.instructions_text_p2.setGeometry(QtCore.QRect(10, 640, 431, 20))
                font = QtGui.QFont()
                font.setPointSize(6)
                self.instructions_text_p2.setFont(font)
                self.instructions_text_p2.setObjectName("instructions_text_p2")
                self.MainWindow_2.addTab(self.p2, "")
                self.board = QtWidgets.QWidget()
                self.board.setObjectName("board")
                
                self.MainWindow_2.addTab(self.board, "")

                
                
                self.ScrollArea = QtWidgets.QScrollArea(self.centralwidget)
                self.ScrollArea.setGeometry(QtCore.QRect(10, 10, 300, 700))
                self.ScrollArea.setLayoutDirection(QtCore.Qt.LeftToRight)
                self.ScrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
                self.ScrollArea.setWidgetResizable(True)
                self.ScrollArea.setObjectName("ScrollArea")
                self.scrollAreaWidgetContents = QtWidgets.QWidget()
                self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 300, 827))
                self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
                self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
                self.verticalLayout_2.setObjectName("verticalLayout_2")


                # for some reason I can't get this to work
                self.win_message = QtWidgets.QLabel(self.board)
                self.win_message.setGeometry(QtCore.QRect(100, 100, 1500, 1500))
                font = QtGui.QFont()
                font.setFamily("Sylfaen")
                font.setPointSize(64)
                self.win_message.setFont(font)
                self.win_message.setObjectName("win_message")
                
                self.ScrollArea.setWidget(self.scrollAreaWidgetContents)
                MainWindow.setCentralWidget(self.centralwidget)
                self.statusbar = QtWidgets.QStatusBar(MainWindow)
                self.statusbar.setObjectName("statusbar")
                MainWindow.setStatusBar(self.statusbar)
                self.actionHello = QtWidgets.QAction(MainWindow)
                self.actionHello.setObjectName("actionHello")

                self.retranslateUi(MainWindow)
                self.MainWindow_2.setCurrentIndex(0)
                QtCore.QMetaObject.connectSlotsByName(MainWindow)

        def retranslateUi(self, MainWindow):
                _translate = QtCore.QCoreApplication.translate
                MainWindow.setWindowTitle(_translate("MainWindow", "Patchwork"))
                for i in range(9):
                        item = self.p1quilt.verticalHeaderItem(i)
                        item.setText(_translate("MainWindow", str(i+1)))
                for i in range(9):
                        item = self.p1quilt.horizontalHeaderItem(i)
                        item.setText(_translate("MainWindow", str(i+1)))
                __sortingEnabled = self.p1quilt.isSortingEnabled()
                self.p1quilt.setSortingEnabled(False)
                self.p1quilt.setSortingEnabled(__sortingEnabled)
                self.turn_marker_p1.setText(_translate("MainWindow", "Player 1\'s Turn"))
                self.turn_marker_p2.setText(_translate("MainWindow", "Player 1\'s Turn"))
                self.turn_marker_board.setText(_translate("MainWindow", "Player 1\'s Turn"))
                self.ErrorMessage_p1.setText(_translate("MainWindow", ""))
                self.MoveAheadButton_p1.setText(_translate("MainWindow", "Move: 1 Space\nReceive: 1 Button"))
                self.PlacePieceButton_p1.setText(_translate("MainWindow", "Place Piece"))
                self.DownloadInstructionsButton_p1.setText(_translate("MainWindow", "Download\nInstructions"))
                self.inventory_p1.setText(_translate("MainWindow", "Income: 0\nButtons: 5\nTime Spaces\nRemaining: 54 \nDistance from Nearest\nIncome: 5"))
                self.win_message.setText(_translate("MainWindow", "hello world!!!"))
                self.instructions_text_p1.setText(_translate("MainWindow", "Use WASD to move, Q to flip, and ER to rotate the pieces"))
                self.MainWindow_2.setTabText(self.MainWindow_2.indexOf(self.p1), _translate("MainWindow", "P1 Quilt"))
                for i in range(9):
                        item = self.p2quilt.verticalHeaderItem(i)
                        item.setText(_translate("MainWindow", str(i+1)))
                for i in range(9):
                        item = self.p2quilt.horizontalHeaderItem(i)
                        item.setText(_translate("MainWindow", str(i+1)))
                __sortingEnabled = self.p2quilt.isSortingEnabled()
                self.p2quilt.setSortingEnabled(False)
                self.p2quilt.setSortingEnabled(__sortingEnabled)
                
                self.ErrorMessage_p2.setText(_translate("MainWindow", ""))
                self.PlacePieceButton_p2.setText(_translate("MainWindow", "Place Piece"))
                self.DownloadInstructionsButton_p2.setText(_translate("MainWindow", "Download\nInstructions"))
                self.inventory_p2.setText(_translate("MainWindow", "Income: 0\nButtons: 5\nTime Spaces\nRemaining: 54 \nDistance from Nearest\nIncome: 5"))
                self.MoveAheadButton_p2.setText(_translate("MainWindow", "Move: 1 Space\nReceive: 1 Button"))
                self.instructions_text_p2.setText(_translate("MainWindow", "Use WASD to move, Q to flip, and ER to rotate the pieces"))
                self.MainWindow_2.setTabText(self.MainWindow_2.indexOf(self.p2), _translate("MainWindow", "P2 Quilt"))                
                self.actionHello.setText(_translate("MainWindow", "Hello!"))

        def create_time_board(self, coor1:tuple = (0,8), coor2:tuple = (0,8), turn:int = 1, patches_gone:int = 0):

                icon = QtGui.QIcon()
                icon.addPixmap(QtGui.QPixmap("images/0.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)

                space_color = {}
                
                self.time_board = QtWidgets.QTableWidget(self.board)
                self.time_board.setGeometry(QtCore.QRect(10, 30, 398, 596))
                self.time_board.setMaximumSize(QtCore.QSize(16777215, 16777215))
                self.time_board.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
                self.time_board.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
                self.time_board.setRowCount(9)
                self.time_board.setColumnCount(6)
                self.time_board.setObjectName("time_board")
                for i in range(6):
                        item = QtWidgets.QTableWidgetItem()
                        self.time_board.setVerticalHeaderItem(i, item)
                for i in range(6):
                        item = QtWidgets.QTableWidgetItem()
                        self.time_board.setHorizontalHeaderItem(i, item)

                space_color[0,0] = (255, 255, 222)
                space_color[0,1] = (255, 255, 218)
                space_color[0,2] = (255, 255, 214)
                space_color[0,3] = (255, 255, 210)
                space_color[0,4] = (255, 255, 206)
                space_color[0,5] = (255, 255, 202)
                space_color[1,0] = (255, 255, 226)
                space_color[1,1] = (255, 255, 126)
                space_color[1,2] = (255, 255, 122)
                space_color[1,3] = (255, 255, 118)
                space_color[1,4] = (255, 255, 114)
                space_color[1,5] = (255, 255, 198)
                space_color[2,0] = (255, 255, 230)
                space_color[2,1] = (255, 255, 130)
                space_color[2,2] = (255, 255, 60)
                space_color[2,3] = (255, 255, 56)
                space_color[2,4] = (255, 255, 108)
                space_color[2,5] = (255, 255, 194)
                space_color[3,0] = (255, 255, 234)
                space_color[3,1] = (255, 255, 134)
                space_color[3,2] = (255, 255, 64)
                space_color[3,3] = (255, 255, 40)
                space_color[3,4] = (255, 255, 104)
                space_color[3,5] = (255, 255, 190)
                space_color[4,0] = (255, 255, 238)
                space_color[4,1] = (255, 255, 138)
                space_color[4,2] = (255, 255, 68)
                space_color[4,3] = (255, 255, 20)
                space_color[4,4] = (255, 255, 100)
                space_color[4,5] = (255, 255, 186)
                space_color[5,0] = (255, 255, 242)
                space_color[5,1] = (255, 255, 142)
                space_color[5,2] = (255, 255, 72)
                space_color[5,3] = (255, 255, 0)
                space_color[5,4] = (255, 255, 96)
                space_color[5,5] = (255, 255, 182)
                space_color[6,0] = (255, 255, 247)
                space_color[6,1] = (255, 255, 146)
                space_color[6,2] = (255, 255, 76)
                space_color[6,3] = (0, 0, 255)
                space_color[6,4] = (255, 255, 92)
                space_color[6,5] = (255, 255, 178)
                space_color[7,0] = (255, 255, 251)
                space_color[7,1] = (255, 255, 150)
                space_color[7,2] = (255, 255, 80)
                space_color[7,3] = (255, 255, 84)
                space_color[7,4] = (255, 255, 88)
                space_color[7,5] = (255, 255, 174)
                space_color[8,0] = (255, 255, 255)
                space_color[8,1] = (255, 255, 154)
                space_color[8,2] = (255, 255, 158)
                space_color[8,3] = (255, 255, 162)
                space_color[8,4] = (255, 255, 166)
                space_color[8,5] = (255, 255, 170)

                patch_coors = [(7,1), (1,1), (4,4), (6,2), (3,3)]
                for i in range(patches_gone):
                        del patch_coors[0]

                for key in space_color:

                        item = QtWidgets.QTableWidgetItem()
                        if key in patch_coors:
                                item.setIcon(icon)
                        y, x = key
                        r, g, b = space_color[key]
                        brush = QtGui.QBrush(QtGui.QColor(r, g, b))
                        brush.setStyle(QtCore.Qt.SolidPattern)
                        item.setBackground(brush)
                        self.time_board.setItem(y, x, item)


                self.time_board.horizontalHeader().setVisible(False)
                self.time_board.horizontalHeader().setDefaultSectionSize(66)
                self.time_board.horizontalHeader().setMinimumSectionSize(32)
                self.time_board.verticalHeader().setVisible(False)
                self.time_board.verticalHeader().setDefaultSectionSize(66)
                self.time_board.verticalHeader().setMinimumSectionSize(32)

                _translate = QtCore.QCoreApplication.translate

                for i in range(6):
                        item = self.time_board.verticalHeaderItem(i)
                        item.setText(_translate("MainWindow", str(i+1)))
                        __sortingEnabled = self.time_board.isSortingEnabled()
                self.time_board.setSortingEnabled(False)
                item = self.time_board.item(0, 3)
                item.setText(_translate("MainWindow", "$"))
                item = self.time_board.item(1, 4)
                item.setText(_translate("MainWindow", "$"))
                item = self.time_board.item(3, 0)
                item.setText(_translate("MainWindow", "$"))
                item = self.time_board.item(3, 2)
                item.setText(_translate("MainWindow", "$"))
                item = self.time_board.item(4, 1)
                item.setText(_translate("MainWindow", "$"))
                item = self.time_board.item(4, 5)
                item.setText(_translate("MainWindow", "$"))
                item = self.time_board.item(6, 3)
                item.setText(_translate("MainWindow", "$ Finish"))
                item = self.time_board.item(7, 4)
                item.setText(_translate("MainWindow", "$"))
                item = self.time_board.item(8, 0)
                item.setText(_translate("MainWindow", "Start"))
                item = self.time_board.item(8, 3)
                item.setText(_translate("MainWindow", "$"))

                if coor1 == coor2:
                        if turn == 1:
                                img = "images/1-2.png"
                        else:
                                img = "images/2-1.png"

                        item = QtWidgets.QTableWidgetItem()

                        icon1 = QtGui.QIcon()
                        icon1.addPixmap(QtGui.QPixmap(img), QtGui.QIcon.Normal, QtGui.QIcon.Off)

                        item.setIcon(icon1)
                        r, g, b = space_color[coor1[1],coor1[0]]
                        brush = QtGui.QBrush(QtGui.QColor(r, g, b))
                        brush.setStyle(QtCore.Qt.SolidPattern)
                        item.setBackground(brush)
                        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
                        brush.setStyle(QtCore.Qt.NoBrush)
                        item.setForeground(brush)
                        self.time_board.setItem(coor1[1], coor1[0], item)
                        
                else: 

                        icon1 = QtGui.QIcon()
                        icon1.addPixmap(QtGui.QPixmap("images/1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
                        icon2 = QtGui.QIcon()
                        icon2.addPixmap(QtGui.QPixmap("images/2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)

                        item = QtWidgets.QTableWidgetItem()

                        item.setIcon(icon1)
                        y, x = coor1
                        r, g, b = space_color[x, y]
                        brush = QtGui.QBrush(QtGui.QColor(r, g, b))
                        brush.setStyle(QtCore.Qt.SolidPattern)
                        item.setBackground(brush)
                        self.time_board.setItem(x, y, item)

                        item = QtWidgets.QTableWidgetItem()

                        item.setIcon(icon2)
                        y, x = coor2
                        r, g, b = space_color[x, y]
                        brush = QtGui.QBrush(QtGui.QColor(r, g, b))
                        brush.setStyle(QtCore.Qt.SolidPattern)
                        item.setBackground(brush)
                        self.time_board.setItem(x, y, item)

                self.time_board.setSortingEnabled(__sortingEnabled)
                self.MainWindow_2.setTabText(self.MainWindow_2.indexOf(self.board), _translate("MainWindow", "Board"))

        def delete_time_board(self):
                self.time_board.setRowCount(0)


if __name__ == "__main__":
        import sys
        app = QtWidgets.QApplication(sys.argv)
        MainWindow = QtWidgets.QMainWindow()
        ui = Ui_MainWindow()
        ui.setupUi(MainWindow)
        MainWindow.show()
        sys.exit(app.exec_())
